name: full-redeploy

env:
  resourceGroupName: 'rg-infinite-words'
  functionAppName: 'infinitewords'
  customDomain: 'api.infinitewords.uk'

on:
  workflow_dispatch:

concurrency: 
    group: infinite-words
    cancel-in-progress: true
    
jobs:
  test-code:
    uses: ./.github/workflows/test-code.yml

  deploy-infrastructure:
    needs: [test-code]
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      resourceGroupName: 'rg-infinite-words'
      functionAppName: 'infinitewords'
      customDomain: 'api.infinitewords.uk'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      salt: ${{ secrets.SALT }}
    
  deploy-functionapp:
    needs: [test-code, deploy-infrastructure]
    uses: ./.github/workflows/deploy-function-app-configure-ssl.yml
    with:
      resourceGroupName: 'rg-infinite-words'
      functionAppName: 'infinitewords'
      customDomain: 'api.infinitewords.uk'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
